### ISSUE TITLE
malloc(): corrupted top size Aborted (core dumped)

### ISSUE THREAD

**Issue by vishal-deka** [numamma/numamma#11]
I am getting this error while running some HPC mini-benchmarks such as XSBench, miniFE, miniAMR. I tried increasing the buffer size but the problem persists. Increasing the buffer size beyond a certain point results in the following error: `Permission error mapping pages.
Consider increasing /proc/sys/kernel/perf_event_mlock_kb,`.
What could be the issue?

**Comment by trahay** [comment]
Hi,
It looks like numamma corrupts the memory. I managed to run XSBench (openmp-threading version) on my laptop with numamma, but miniFE crashed. The problems seems to happen during MPI initialization when hwloc initializes.
I will try to investigate in the next few days.

**Comment by trahay** [comment]
Hi,
After investigation, the problems comes from numamma handling of calls to `calloc`. Commit #f77f97d fixes this problem and, on my laptop, I was able to run miniFE.
Could you update your copy of numamma and try again ?

**Comment by vishal-deka** [comment]
Yes it is working now. Thanks a lot.
