### ISSUE TITLE
Reasoning about result for store events

### ISSUE THREAD

**Issue by jklinkenberg** [numamma/numamma#13]
Hi,

I created a small sample code that 
* allocates a large buffer
* initializes the buffer (linear accesses)
* uses the buffer in many iterations but only in a reading fashion (linear access)

Additionally I 
* disabled all pretechers on the system
* and used a low sampling frequency for numamma to get a more detailed picture

So, in theory there **should be much more load samples than store samples**. What I see for the corresponding buffer is the following:
```bash
# --------------------------------------
# Summary of all the read memory access:
# Total count          :         1025
# Total weigh          :         194745
# L1 Hit        : 283 (27.609756 %)     min: 0 cycles   max: 0 cycles    avg: 8 cycles  total weight: 2311 (1.186680 %)
# L3 Hit        : 15 (1.463415 %)       min: 0 cycles   max: 0 cycles    avg: 76 cycles total weight: 1143 (0.586921 %)
# LFB Hit       : 673 (65.658537 %)     min: 0 cycles   max: 0 cycles    avg: 254 cycles        total weight: 171532 (88.080310 %)
# Local RAM Hit : 54 (5.268293 %)       min: 0 cycles   max: 0 cycles    avg: 365 cycles        total weight: 19759 (10.146088 %)

# --------------------------------------
# Summary of all the write memory access:
# Total count          :         3007
# Total weigh          :         0
# L1 Hit        : 2940 (97.771866 %)    min: 0 cycles   max: 0 cycles    avg: 0 cycles  total weight: 0 (0.000000 %)
```

## My Observations
*  The distribution for load events seems to go in the right direction as there are some cache misses but most of the data will come from LFB or cache
* There are much more store samples than load samples **OR** there are many load samples missing

## Problem / Question:
I would expect to see a similar distribution for write accesses (1 miss and 7 hits in cache) but it says 97.77% from cache for that buffer.
Most systems only modify data in cache if no explicit compile flags are used to force write-through operations. That means data has to be loaded to cache first.
* **Q1:** Can I trust the write numbers at all then?
* **Q2:** It seems exactly these load operations before write operations that modify data in cache are not covered in the recording/analysis. Or are they included in the read samples? If not, is there any way to include those with PEBS?
    * If I only enable the writing section in the code I see 0 read events and there are still 97% L1_Hits in the dump. This is why I assumed these load operations are not covered

**Comment by trahay** [comment]
Hi,
**Q1:**
The low number of read events may be due to missing events. You can try changing the buffer size (eg, with `-s 262144`), or setting an alarm (eg. `-a 5`)

To get an idea of the number of read/write events, you can run your application with `perf mem record` and check the number of samples reported by `perf mem report`.

**Q2**
I think this kind of operations are already covered by PEBS, but numamma misses samples.

**Comment by jklinkenberg** [comment]
Thanks for your response. I will play around a bit with buffer sizes and alarm.
