### ISSUE TITLE
Problem at runtime with DWARF version

### ISSUE THREAD

**Issue by SeiDPierre** [numamma/numamma#17]
Hello, 
I've recently installed numamma package on my machine. At runtime using lulesh2.0 or BabelStream, I get:
`ERROR: unrecognized DWARF version in .debug_info at 6 (0)`
This kind of message does not appear when running with stream app.

My config is 
gcc (Debian 11.3.0-12) 11.3.0
kernel 6.5.0-0-amd64
cmake version 3.25.1

I've tried to run it with a more recent version of libelf without success. Also, the libelf used in the `install_everything.sh` script cant compile because of some deprecated usages such as:
`../../debuginfod/debuginfod-client.c:983:7: warning: ‘CURLOPT_PROTOCOLS’ is deprecated: since 7.85.0. Use CURLOPT_PROTOCOLS_STR [-Wdeprecated-declarations]
`
I had to add `CFLAGS=-Wno-error=deprecated-declarations` option so that it could compile.

Would you have any recommandations to compile it properly? (gcc version, etc)
Thanks, 
Pierre

**Comment by SeiDPierre** [comment]
It works with gcc/g++-10 :)

**Comment by trahay** [comment]
Thanks for the bug report !

I've updated the installation script to:
- use the latest version of libelf (version 0.190). This fixes the error about `curl`.
- use the latest (git) version of libbacktrace.  This fixes the error about the DWARF version.

I didn't test this with many settings, but it seem to work fine on my machine with gcc 13.2.0.

**Comment by SeiDPierre** [comment]
Thanks, I'll give a try with advised versions.

**Comment by SeiDPierre** [comment]
I realized that I was getting some warning messages from cmake when finally reaching numamma. (Last step of the install_everything.sh script). The warning was about the `-DLIBELF_DIR=$LIBELF_INSTALL_ROOT` option. In deed the LIBELF_DIR variable is neither used in CMakeLists.txt nor in Findlibelf.cmake. As a consequence, you cant use your manually installed elf libs. I just added some HINTS in the Findlibelf.cmake and it solved it. Attached is the file I modified if it helps ;)
[findlibelf.tar.gz](https://github.com/numamma/numamma/files/13919495/findlibelf.tar.gz)

**Comment by SeiDPierre** [comment]
> Thanks for the bug report !
> 
> I've updated the installation script to:
> 
>     * use the latest version of libelf (version 0.190). This fixes the error about `curl`.
> 
>     * use the latest (git) version of libbacktrace.  This fixes the error about the DWARF version.
> 
> 
> I didn't test this with many settings, but it seem to work fine on my machine with gcc 13.2.0.

Everything worked on my side too. Thanks!

**Comment by trahay** [comment]
Thanks for the patch ! I've added it to numamma.
