### ISSUE TITLE
numaMMA with Coral2's benchmark quicksilver is endless

### ISSUE THREAD

**Issue by SeiDPierre** [numamma/numamma#22]
Hello, 
I've been running numaMMA with different hpc benchmarks and everything was going fine until I met quicksilver app:
(See for details : https://asc.llnl.gov/coral-2-benchmarks Coral 2 website.
i'm running the Problem1 benchmark and a regular run takes 80s with16 OpenMP threads and NO mpi. 

As soon as I run it with numaMMA, it runs for ever. I tried 3 runs and it can last for 120h without any results or info in a log file. Only 1 core is running among the 16 requested.
Here is the command how I'm running things (qs is the executable and requires a file.inp as an input):
```
numamma --alarm=100 --sampling-rate=1000 --buffer-size=512 -d -D --outputdir=result/test -- \
    ${PATH}/qs "-i h2m.inp" &> example.log
```
Any hint would be appreciated!

**Comment by trahay** [comment]
Hi,
I tried running quicksilver with numamma on my laptop (OpenMP, no MPI, 8 threads) and it works (without providing any file.inp).
If numamma hangs, you first need to identify where is the problem. Does the application works ? You should see the application steps being printed.
If there's only one core being used, it's probably stuck after the application, when numamma tries to match addresses with memory objects (numamma probably prints a "NumaMMA report" message before that)

You can also try using gdb:
```
$ gdb -p  PID    # where PID is the PID of the program
[...]
(gdb) bt
[...]
```

**Comment by SeiDPierre** [comment]
Problem solved. Nothing to do with numaMMA.. I was using the input file of quicksiver in a wrong manner... (And it was ok before writing the script for nummamma usage :) )
Sorry about that!
