### ISSUE TITLE
 [numactl] minor/major linkage issues

### ISSUE THREAD

**Issue by gureya** [numamma/numamma#5]
Description:

/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `minor'
/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `major'

Additional info:
* package version(s): 2.0.11-2

The fix is upstream commit https://github.com/numactl/numactl/commit/25691a084a2012a339395ade567dbae814e237e9

Which is also available as release v2.0.12 (and the package is flagged out of date).

Replace the numactl version in the install_everything.sh script

**Comment by trahay** [comment]
Thanks !
I upgraded the installation script so that it uses numactl v2.0.12.
